Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/models/order.rb
    - lib/pago.rb
    - bin/bundle
    - db/migrate/20220127094158_create_active_storage_tables.active_storage.rb

Metrics/BlockLength:
  Exclude:
    - app/views/products/who_bought.atom.builder
    - db/schema.rb
    - test/system/orders_test.rb
    - config/environments/development.rb
    - config/environments/production.rb

Metrics/AbcSize:
  Exclude:
    - app/models/order.rb
    - lib/pago.rb
    - app/controllers/application_controller.rb
    - db/migrate/20220127094158_create_active_storage_tables.active_storage.rb

Style/GuardClause:
  Exclude:
    - app/models/order.rb
    - app/controllers/application_controller.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Lint/UnusedMethodArgument:
  Exclude:
    - lib/pago.rb

Lint/UselessAssignment:
  Exclude:
     - test/mailboxes/support_mailbox_test.rb